---
- name: Removing provsioner SSH keys
  import_role:
    name: remove_provision_keys

- name: Set up MOTD
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: Writing creds into file
  copy:
    dest: '/home/{{ username }}/.credentials'
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}

      # ELK creds
      Elastic password: {{ elastic_password }}
      Kibana system password: {{ kibana_system_password }}
      Logstash system password: {{ logstash_system_password }}
      Beats system password: {{ beats_system_password }}

