---
- name: Removing provsioner SSH keys
  import_role:
    name: remove_provision_keys

# Add ssh pub keys
- name: Add SSH public keys
  import_role:
    name: sshkey

# Secure ssh auth
- name: Disable root login
  import_role: 
    name: securessh
  when: disable_root is defined

#- name: Adding account keys to root user
#  copy:
#    src: '{{ authorized_keys_file.stat.path }}'
#    dest: '/root/.ssh/authorized_keys'
#    mode: '0600'
#    owner: "root"
#    group: "root"
#  when:
#    - authorized_keys_file.stat.exists
#    - authorized_keys_file.stat.size > 0

- name: Set up MOTD
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: Writing creds into file
  copy:
    dest: '/home/{{ username }}/.credentials'
    mode: '0600'
    owner: '{{ username }}'
    group: '{{ username }}'
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}

      # ELK creds
      Elastic password: {{ elasticsearch_password }}
      Kibana system password: {{ kibana_system_password }}
      Logstash ingest user: {{ logstash_ingest_username }}
      Logstash ingest password: {{ logstash_ingest_password}}
