---
- name: Create Elasticsearch host list
  set_fact:
    elasticsearch_hosts: "{{ data.elasticsearch | map(attribute='instance.hostname') | list }}"
    cacheable: true
  run_once: true
  delegate_to: localhost

- name: Backup Elasticsearch config
  copy:
    src: "{{ elasticsearch_config }}"
    dest: "{{ elasticsearch_config }}.bak"
    remote_src: true
    owner: elasticsearch
    group: elasticsearch
    mode: 0644
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"

- name: Update Elasticsearch config
  template:
    src: templates/elasticsearch.yml.j2
    dest: "{{ elasticsearch_config }}"
    owner: elasticsearch
    group: elasticsearch
    mode: 0644
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"
  loop_control:
    index_var: count   

- name: Restart Elasticsearch
  systemd_service:
    name: elasticsearch
    state: restarted
    enabled: true
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"