---

# Create cert directory in cluster
- name: Create Elasticsearch ssl directory
  file:
    path: "{{ elasticsearch_ssl_directory }}"
    state: directory
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"

- name: Create Logstsh ssl directory
  file:
    path: "{{ logstash_ssl_directory }}"
    state: directory
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['logstash'] }}"

- name: Create Kibana ssl directory
  file:
    path: "{{ kibana_ssl_directory }}"
    state: directory
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"  

# Copy over certs to cluster

# Elasticsearch
- name: Copy Elasticsearch cert
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.elasticsearch[count].instance.hostname }}/{{ data.elasticsearch[count].instance.hostname }}.crt"
    dest: "{{ elasticsearch_ssl_directory }}/{{ data.elasticsearch[count].instance.hostname }}.crt"
    owner: elasticsearch
    group: elasticsearch
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"
  loop_control:
    index_var: count

- name: Copy Elasticsearch key
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.elasticsearch[count].instance.hostname }}/{{ data.elasticsearch[count].instance.hostname }}.key"
    dest: "{{ elasticsearch_ssl_directory }}/{{ data.elasticsearch[count].instance.hostname }}.key"
    owner: elasticsearch
    group: elasticsearch
    mode: 0600
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"
  loop_control:
    index_var: count

- name: Copy Elasticsearch CSR
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.elasticsearch[count].instance.hostname }}/{{ data.elasticsearch[count].instance.hostname }}.csr"
    dest: "{{ elasticsearch_ssl_directory }}/{{ data.elasticsearch[count].instance.hostname }}.csr"
    owner: elasticsearch
    group: elasticsearch
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"
  loop_control:
    index_var: count

- name: Copy over CA to Elasticsearch host
  copy:
    src: "{{ cluster_ssl_ca_directory }}/ca.crt"
    dest: "{{ elasticsearch_ssl_directory }}/ca.crt"
    owner: elasticsearch
    group: elasticsearch
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['elasticsearch'] }}"

# Logstash
- name: Copy Logstash cert
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.logstash[count].instance.hostname }}/{{ data.logstash[count].instance.hostname }}.crt"  
    dest: "{{ logstash_ssl_directory }}/{{ data.logstash[count].instance.hostname }}.crt"
    owner: logstash
    group: logstash
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['logstash'] }}"
  loop_control:
    index_var: count

- name: Copy Logstash key
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.logstash[count].instance.hostname }}/{{ data.logstash[count].instance.hostname }}.key"  
    dest: "{{ logstash_ssl_directory }}/{{ data.logstash[count].instance.hostname }}.key"
    owner: logstash
    group: logstash
    mode: 0600
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['logstash'] }}"
  loop_control:
    index_var: count

- name: Copy Logstash CSR
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.logstash[count].instance.hostname }}/{{ data.logstash[count].instance.hostname }}.csr"  
    dest: "{{ logstash_ssl_directory }}/{{ data.logstash[count].instance.hostname }}.csr"
    owner: logstash
    group: logstash
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['logstash'] }}"
  loop_control:
    index_var: count

- name: Copy over CA to Logstash host
  copy:
    src: "{{ cluster_ssl_ca_directory }}/ca.crt"
    dest: "{{ logstash_ssl_directory }}/ca.crt"
    owner: logstash
    group: logstash
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['logstash'] }}"

# Kibana

- name: Copy Kibana cert
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.kibana[count].instance.hostname }}/{{ data.kibana[count].instance.hostname }}.crt"  
    dest: "{{ kibana_ssl_directory }}/{{ data.kibana[count].instance.hostname }}.crt"
    owner: kibana
    group: kibana
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"
  loop_control:
    index_var: count

- name: Copy Kibana key
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.kibana[count].instance.hostname }}/{{ data.kibana[count].instance.hostname }}.key"  
    dest: "{{ kibana_ssl_directory }}/{{ data.kibana[count].instance.hostname }}.key"
    owner: kibana
    group: kibana
    mode: 0600
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"
  loop_control:
    index_var: count  

- name: Copy Kibana CSR
  copy:
    src: "{{ cluster_ssl_directory }}/{{ data.kibana[count].instance.hostname }}/{{ data.kibana[count].instance.hostname }}.csr"  
    dest: "{{ kibana_ssl_directory }}/{{ data.kibana[count].instance.hostname }}.csr"
    owner: kibana
    group: kibana
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"
  loop_control:
    index_var: count

- name: Copy over CA to Kibana host
  copy:
    src: "{{ cluster_ssl_ca_directory }}/ca.crt"
    dest: "{{ kibana_ssl_directory }}/ca.crt"
    owner: kibana
    group: kibana
    mode: 0664
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"