---
- name: Install nginx
  apt:
    pkg:
      - nginx-full
    state: latest
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"

- name: Add nginx config
  template:
    src: 'templates/vhost.conf.j2'
    dest: '/etc/nginx/sites-available/{{ _domain }}'
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"    

- name: Enable vhost config
  file:
    src: '/etc/nginx/sites-available/{{ _domain }}'
    dest: '/etc/nginx/sites-enabled/{{ _domain }}'
    state: link
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"

- name: Remove default Nginx vhost
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['provisioner'] }}"    
  notify: restart nginx
  
# Configure SSL

- name: Configuring SSL on {{ _domain }}
  import_role:
    name: certbot_ssl
  vars:
    host: "{{ groups['provisioner'][0] }}"
    webserver_stack: lemp