---
- name: Set elasticsearch password reset path
  set_fact:
    elasticsearch_reset_password: 
      /usr/share/elasticsearch/bin/elasticsearch-reset-password
  run_once: true
  delegate_to: localhost

- name: Reseting elastic password
  shell:
    cmd: |
      echo y | {{ elasticsearch_reset_password }} -s -u elastic
  run_once: true
  delegate_to: "{{ groups['elasticsearch'][0] }}"
  register: elastic_password_output

- name: Reseting kibana_system
  shell:
    cmd: |
      echo y | {{ elasticsearch_reset_password }} -s -u kibana_system
  run_once: true
  delegate_to: "{{ groups['elasticsearch'][0] }}"
  register: kiabana_password_output

- name: Reseting logstash_system
  shell:
    cmd: |
      echo y | {{ elasticsearch_reset_password }} -s -u logstash_system
  run_once: true
  delegate_to: "{{ groups['elasticsearch'][0] }}"
  register: logstash_password_output

- name: Reseting beats_system
  shell:
    cmd: |
      echo y | {{ elasticsearch_reset_password }} -s -u beats_system
  run_once: true
  delegate_to: "{{ groups['elasticsearch'][0] }}"
  register: beats_password_output

- name: Set password variables
  set_fact:
    elastic_password: "{{ elastic_password_output.stdout }}"
    kibana_system_password: "{{ kiabana_password_output.stdout }}"
    logstash_system_password: "{{ logstash_password_output.stdout }}"
    beats_system_password: "{{ beats_password_output.stdout }}"
    cacheable: true
  run_once: true
  delegate_to: localhost