---
# destroy instances

- name: Destroying instances 
  hosts: localhost
  connection: local
  vars_files:
      - group_vars/linode/vars

  tasks:
  - name: Deleting Elasticsearch instances
    linode.cloud.instance:
      label: 'elasticsearch{{ item }}-{{ uuid }}'
      api_token: '{{ token_password }}'
      state: absent
    with_sequence: count='{{ elasticsearch_cluster_size }}'

  - name: Deleting Logstash instances
    linode.cloud.instance:
      label: 'logstash{{ item }}-{{ uuid }}'
      api_token: '{{ token_password }}'
      state: absent
    with_sequence: count='{{ logstash_cluster_size }}'