---
- name: Install ufw
  apt:
    pkg:
    - ufw
    state: present

- name: UFW allow outgoing
  ufw:
    direction: outgoing
    policy: allow

- name: UFW allow incoming
  ufw:
    direction: incoming
    policy: allow    