---
# add keys when deployed with account keys
- name: Checking account keys
  stat:
    path: '/root/.ssh/authorized_keys'
  register: authorized_keys_file
  run_once: true
  delegate_to: localhost

- name: Adding account keys to sudo user
  copy:
    src: '{{ authorized_keys_file.stat.path }}'
    dest: '/home/{{ username }}/.ssh/authorized_keys'
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
  when:
    - authorized_keys_file.stat.exists
    - authorized_keys_file.stat.size > 0