---
- name: Secure ssh config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '^\#?PermitRootLogin (yes|no)', replace: 'PermitRootLogin no' }
    - { search: '^\#?PasswordAuthentication (yes|no)', replace: 'PasswordAuthentication no' }
    - { search: '^\#?PubkeyAuthentication (yes|no)', replace: 'PubkeyAuthentication yes' }
  notify: restart ssh
  when: 
    - disable_root is defined
    - authorized_keys_file.stat.exists
    - authorized_keys_file.stat.size > 0

# If root login is disabled and they don't provide an SSH KEY
- name: Secure ssh config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.search }}"
    line: "{{ item.replace }}"
  loop:
    - { search: '^\#?PermitRootLogin (yes|no)', replace: 'PermitRootLogin no' }
  notify: restart ssh
  when: 
    - disable_root is defined
    - authorized_keys_file is not defined