---

# Helper: certbot_ssl
#
# Allows us to configure SSL for a web endpoint in
# a clustered environment.
#
# When using this helper the task, must include 
# the following variables:
# - host
# - webserver_task
# 
# Example:
#
#   - name: Configuring SSL on {{ _domain }}
#     import_role:
#       name: certbot_ssl
#     vars:
#       host: "{{ groups['provisioner'][0] }}"
#       webserver_stack: lemp
#
# This role is delegated to SINGLE host where
# domain validation (DV) is performed.

- name: Install nginx certbot plugin
  include_tasks:
    file: nginx-certbot.yml
  when: webserver_stack == 'lemp'