---
- name: Install python3-certbot-nginx
  apt:
    name: python3-certbot-nginx
    state: present
  run_once: true
  delegate_to: "{{ host }}"

- name: Set certbot plugin
  set_fact:
    certbot_plugin: nginx
    cacheable: yes
  run_once: true
  delegate_to: "{{ host }}"    

- name: Installing let's encrypt certificate on subdomain provided via UDF
  shell:
    cmd: "certbot -n --nginx --agree-tos --redirect -d {{ subdomain }}.{{ domain }} -m {{ soa_email_address }}"
  run_once: true
  delegate_to: "{{ host }}"    
  when:
    - domain is defined
    - subdomain != 'www'

- name: installing let's encrypt certificate on tld and default subdomain provided via UDF
  shell:
    cmd: "certbot -n --nginx --agree-tos --redirect -d {{ domain }} -d {{ subdomain }}.{{ domain }} -m {{ soa_email_address }}"
  run_once: true
  delegate_to: "{{ host }}"    
  when:
    - domain is defined
    - subdomain == 'www'

- name: installing let's encrypt certificate on default domain
  shell:
    cmd: "certbot -n --nginx --agree-tos --redirect -d {{ default_dns }} -m {{ soa_email_address }}"
  run_once: true
  delegate_to: "{{ host }}"    
  when: default_dns is defined